### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by izumin5210** [izumin5210/grpc-basicauth#2]
- feature
    - [x] Uses secure comparison
    - [ ] Adds example tests
- testing
    - [ ] skipped method
    - [ ] invalid schema
    - [ ] [`ServiceAuthFuncOverride`](https://godoc.org/github.com/grpc-ecosystem/go-grpc-middleware/auth#ServiceAuthFuncOverride)
- misc
    - [ ] example in readme
